name: Production Environment Deployment
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy to Production Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: pulumi/auth-actions@v1
        with:
          organization: team-ce
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:laci-pulumi-corp
      - name: Preview Changes
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: team-ce/prod
          upsert: true
      - name: Deploy Changes
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: team-ce/prod
          upsert: true 